[workspace]
members = [".", "tree-sitter-cypherdoc", "tools/cypher"]
resolver = "2"

[workspace.package]
version = "0.2.2"
license = "MIT"
repository = "https://github.com/gram-data/tree-sitter-cypher"
edition = "2021"

[package]
name = "tree-sitter-cypher"
description = "Graph query language"
version = "0.2.2"
authors = ["Andreas Kollegger <andreas.kollegger@neo4j.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "cypher"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/gram-data/tree-sitter-cypher"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.5"
