[package]
name = "tree-sitter-cypherdoc"
description = "Structured documentation comments for Cypher statements"
version = "0.0.1"
authors = ["Andreas Kollegger <andreas.kollegger@neo4j.com>"]
license = "MIT"
keywords = ["incremental", "parsing", "tree-sitter", "cypherdoc", "cypher"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/gram-data/tree-sitter-cypher"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.5"
