/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_STAR_STAR = 1,
  anon_sym_STAR_SLASH = 2,
  aux_sym_name_token1 = 3,
  sym_description_line = 4,
  anon_sym_ATparam = 5,
  anon_sym_ATreturns = 6,
  anon_sym_LBRACK = 7,
  anon_sym_EQ = 8,
  anon_sym_RBRACK = 9,
  aux_sym_string_default_token1 = 10,
  aux_sym_string_default_token2 = 11,
  sym_number_default = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_COMMA = 17,
  anon_sym_COLON = 18,
  sym_array_marker = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  sym_tag_description = 22,
  sym_document = 23,
  sym_name = 24,
  sym_description = 25,
  sym_param_tag = 26,
  sym_returns_tag = 27,
  sym_required_param = 28,
  sym_optional_param = 29,
  sym_param_default = 30,
  sym_string_default = 31,
  sym_boolean_default = 32,
  sym_type_annotation = 33,
  sym_returns_type_annotation = 34,
  sym_tuple_type = 35,
  sym_tuple_member = 36,
  sym_scalar_type = 37,
  sym_type_argument = 38,
  sym_identifier = 39,
  aux_sym_document_repeat1 = 40,
  aux_sym_description_repeat1 = 41,
  aux_sym_tuple_type_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_STAR_STAR] = "/**",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_name_token1] = "name_token1",
  [sym_description_line] = "description_line",
  [anon_sym_ATparam] = "@param",
  [anon_sym_ATreturns] = "@returns",
  [anon_sym_LBRACK] = "[",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACK] = "]",
  [aux_sym_string_default_token1] = "string_default_token1",
  [aux_sym_string_default_token2] = "string_default_token2",
  [sym_number_default] = "number_default",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_array_marker] = "array_marker",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_tag_description] = "tag_description",
  [sym_document] = "document",
  [sym_name] = "name",
  [sym_description] = "description",
  [sym_param_tag] = "param_tag",
  [sym_returns_tag] = "returns_tag",
  [sym_required_param] = "required_param",
  [sym_optional_param] = "optional_param",
  [sym_param_default] = "param_default",
  [sym_string_default] = "string_default",
  [sym_boolean_default] = "boolean_default",
  [sym_type_annotation] = "type_annotation",
  [sym_returns_type_annotation] = "returns_type_annotation",
  [sym_tuple_type] = "tuple_type",
  [sym_tuple_member] = "tuple_member",
  [sym_scalar_type] = "scalar_type",
  [sym_type_argument] = "type_argument",
  [sym_identifier] = "identifier",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_STAR_STAR] = anon_sym_SLASH_STAR_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_name_token1] = aux_sym_name_token1,
  [sym_description_line] = sym_description_line,
  [anon_sym_ATparam] = anon_sym_ATparam,
  [anon_sym_ATreturns] = anon_sym_ATreturns,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_string_default_token1] = aux_sym_string_default_token1,
  [aux_sym_string_default_token2] = aux_sym_string_default_token2,
  [sym_number_default] = sym_number_default,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_array_marker] = sym_array_marker,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_tag_description] = sym_tag_description,
  [sym_document] = sym_document,
  [sym_name] = sym_name,
  [sym_description] = sym_description,
  [sym_param_tag] = sym_param_tag,
  [sym_returns_tag] = sym_returns_tag,
  [sym_required_param] = sym_required_param,
  [sym_optional_param] = sym_optional_param,
  [sym_param_default] = sym_param_default,
  [sym_string_default] = sym_string_default,
  [sym_boolean_default] = sym_boolean_default,
  [sym_type_annotation] = sym_type_annotation,
  [sym_returns_type_annotation] = sym_returns_type_annotation,
  [sym_tuple_type] = sym_tuple_type,
  [sym_tuple_member] = sym_tuple_member,
  [sym_scalar_type] = sym_scalar_type,
  [sym_type_argument] = sym_type_argument,
  [sym_identifier] = sym_identifier,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATparam] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATreturns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_default_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_default_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number_default] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_array_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_description] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_param_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_required_param] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_default] = {
    .visible = true,
    .named = true,
  },
  [sym_string_default] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_default] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_member] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_column = 2,
  field_default = 3,
  field_description = 4,
  field_name = 5,
  field_param = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_column] = "column",
  [field_default] = "default",
  [field_description] = "description",
  [field_name] = "name",
  [field_param] = "param",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_param, 2},
    {field_type, 1},
  [4] =
    {field_description, 2},
    {field_type, 1},
  [6] =
    {field_description, 3},
    {field_param, 2},
    {field_type, 1},
  [9] =
    {field_value, 0},
  [10] =
    {field_argument, 2},
    {field_name, 0},
  [12] =
    {field_column, 0},
    {field_type, 2},
  [14] =
    {field_default, 3},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '"', 4,
        '\'', 5,
        '*', 9,
        ',', 78,
        '-', 32,
        '/', 8,
        ':', 79,
        '<', 81,
        '=', 66,
        '>', 82,
        '@', 22,
        '[', 65,
        ']', 67,
        'f', 38,
        't', 42,
        '{', 76,
        '}', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(46);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '@') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(46);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 4,
        '\'', 5,
        '*', 9,
        ',', 78,
        '-', 32,
        '/', 8,
        ':', 79,
        '<', 81,
        '=', 66,
        '>', 82,
        '@', 22,
        '[', 65,
        ']', 67,
        'f', 38,
        't', 42,
        '{', 76,
        '}', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') SKIP(31);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == 'f') ADVANCE(15);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead == '}') ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(35);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '*', 10,
        ',', 78,
        '-', 83,
        ':', 79,
        '<', 81,
        '=', 66,
        '>', 82,
        '@', 22,
        '[', 64,
        ']', 67,
        '}', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(80);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(60);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(13);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 31:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'a') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'e') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'e') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'l') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'r') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 's') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'u') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\t') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '@') ADVANCE(53);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(59);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'm') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'p') ADVANCE(48);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 's') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 't') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATparam);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATparam);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_ATreturns);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_ATreturns);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ']') ADVANCE(80);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_string_default_token1);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_default_token2);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number_default);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number_default);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_array_marker);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_tag_description);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [aux_sym_name_token1] = ACTIONS(1),
    [anon_sym_ATparam] = ACTIONS(1),
    [anon_sym_ATreturns] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_string_default_token1] = ACTIONS(1),
    [aux_sym_string_default_token2] = ACTIONS(1),
    [sym_number_default] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_array_marker] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(45),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(5), 11,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      anon_sym_EQ,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_GT,
      sym_tag_description,
  [14] = 7,
    ACTIONS(7), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(9), 1,
      sym_description_line,
    ACTIONS(11), 1,
      anon_sym_ATparam,
    ACTIONS(13), 1,
      anon_sym_ATreturns,
    STATE(5), 1,
      sym_description,
    STATE(10), 1,
      aux_sym_description_repeat1,
    STATE(7), 3,
      sym_param_tag,
      sym_returns_tag,
      aux_sym_document_repeat1,
  [38] = 5,
    ACTIONS(17), 1,
      sym_number_default,
    STATE(50), 1,
      sym_param_default,
    ACTIONS(15), 2,
      aux_sym_string_default_token1,
      aux_sym_string_default_token2,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(51), 2,
      sym_string_default,
      sym_boolean_default,
  [57] = 4,
    ACTIONS(21), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(23), 1,
      anon_sym_ATparam,
    ACTIONS(25), 1,
      anon_sym_ATreturns,
    STATE(6), 3,
      sym_param_tag,
      sym_returns_tag,
      aux_sym_document_repeat1,
  [72] = 4,
    ACTIONS(23), 1,
      anon_sym_ATparam,
    ACTIONS(25), 1,
      anon_sym_ATreturns,
    ACTIONS(27), 1,
      anon_sym_STAR_SLASH,
    STATE(8), 3,
      sym_param_tag,
      sym_returns_tag,
      aux_sym_document_repeat1,
  [87] = 4,
    ACTIONS(21), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(23), 1,
      anon_sym_ATparam,
    ACTIONS(25), 1,
      anon_sym_ATreturns,
    STATE(8), 3,
      sym_param_tag,
      sym_returns_tag,
      aux_sym_document_repeat1,
  [102] = 4,
    ACTIONS(29), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(31), 1,
      anon_sym_ATparam,
    ACTIONS(34), 1,
      anon_sym_ATreturns,
    STATE(8), 3,
      sym_param_tag,
      sym_returns_tag,
      aux_sym_document_repeat1,
  [117] = 4,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    STATE(15), 1,
      sym_identifier,
    STATE(17), 2,
      sym_required_param,
      sym_optional_param,
  [131] = 3,
    ACTIONS(43), 1,
      sym_description_line,
    STATE(11), 1,
      aux_sym_description_repeat1,
    ACTIONS(41), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [143] = 3,
    ACTIONS(47), 1,
      sym_description_line,
    STATE(11), 1,
      aux_sym_description_repeat1,
    ACTIONS(45), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [155] = 1,
    ACTIONS(50), 4,
      anon_sym_STAR_SLASH,
      sym_description_line,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [162] = 2,
    ACTIONS(54), 1,
      sym_tag_description,
    ACTIONS(52), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [171] = 2,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(56), 3,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [180] = 1,
    ACTIONS(60), 4,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      sym_tag_description,
  [187] = 1,
    ACTIONS(62), 4,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      sym_tag_description,
  [194] = 2,
    ACTIONS(66), 1,
      sym_tag_description,
    ACTIONS(64), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [203] = 1,
    ACTIONS(68), 4,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      sym_tag_description,
  [210] = 1,
    ACTIONS(70), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [216] = 3,
    ACTIONS(72), 1,
      anon_sym_RBRACK,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(20), 1,
      aux_sym_tuple_type_repeat1,
  [226] = 3,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    STATE(24), 1,
      sym_tuple_member,
    STATE(42), 1,
      sym_identifier,
  [236] = 3,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    STATE(43), 1,
      sym_type_argument,
    STATE(44), 1,
      sym_identifier,
  [246] = 1,
    ACTIONS(77), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [252] = 3,
    ACTIONS(79), 1,
      anon_sym_RBRACK,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(27), 1,
      aux_sym_tuple_type_repeat1,
  [262] = 3,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    STATE(14), 1,
      sym_identifier,
    STATE(40), 1,
      sym_scalar_type,
  [272] = 3,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    STATE(36), 1,
      sym_tuple_member,
    STATE(42), 1,
      sym_identifier,
  [282] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      aux_sym_tuple_type_repeat1,
  [292] = 3,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    STATE(14), 1,
      sym_identifier,
    STATE(39), 1,
      sym_scalar_type,
  [302] = 1,
    ACTIONS(85), 3,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [308] = 2,
    ACTIONS(87), 1,
      aux_sym_name_token1,
    STATE(3), 1,
      sym_name,
  [315] = 2,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_returns_type_annotation,
  [322] = 2,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_type_annotation,
  [329] = 2,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    STATE(46), 1,
      sym_tuple_type,
  [336] = 2,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    ACTIONS(97), 1,
      sym_array_marker,
  [343] = 1,
    ACTIONS(99), 2,
      aux_sym_name_token1,
      anon_sym_LBRACK,
  [348] = 1,
    ACTIONS(72), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [353] = 2,
    ACTIONS(37), 1,
      aux_sym_name_token1,
    STATE(41), 1,
      sym_identifier,
  [360] = 2,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(103), 1,
      sym_array_marker,
  [367] = 1,
    ACTIONS(105), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [372] = 1,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
  [376] = 1,
    ACTIONS(109), 1,
      anon_sym_EQ,
  [380] = 1,
    ACTIONS(111), 1,
      anon_sym_COLON,
  [384] = 1,
    ACTIONS(113), 1,
      anon_sym_GT,
  [388] = 1,
    ACTIONS(115), 1,
      anon_sym_GT,
  [392] = 1,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
  [396] = 1,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
  [400] = 1,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
  [404] = 1,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
  [408] = 1,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
  [412] = 1,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
  [416] = 1,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
  [420] = 1,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
  [424] = 1,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
  [428] = 1,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
  [432] = 1,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 87,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 117,
  [SMALL_STATE(10)] = 131,
  [SMALL_STATE(11)] = 143,
  [SMALL_STATE(12)] = 155,
  [SMALL_STATE(13)] = 162,
  [SMALL_STATE(14)] = 171,
  [SMALL_STATE(15)] = 180,
  [SMALL_STATE(16)] = 187,
  [SMALL_STATE(17)] = 194,
  [SMALL_STATE(18)] = 203,
  [SMALL_STATE(19)] = 210,
  [SMALL_STATE(20)] = 216,
  [SMALL_STATE(21)] = 226,
  [SMALL_STATE(22)] = 236,
  [SMALL_STATE(23)] = 246,
  [SMALL_STATE(24)] = 252,
  [SMALL_STATE(25)] = 262,
  [SMALL_STATE(26)] = 272,
  [SMALL_STATE(27)] = 282,
  [SMALL_STATE(28)] = 292,
  [SMALL_STATE(29)] = 302,
  [SMALL_STATE(30)] = 308,
  [SMALL_STATE(31)] = 315,
  [SMALL_STATE(32)] = 322,
  [SMALL_STATE(33)] = 329,
  [SMALL_STATE(34)] = 336,
  [SMALL_STATE(35)] = 343,
  [SMALL_STATE(36)] = 348,
  [SMALL_STATE(37)] = 353,
  [SMALL_STATE(38)] = 360,
  [SMALL_STATE(39)] = 367,
  [SMALL_STATE(40)] = 372,
  [SMALL_STATE(41)] = 376,
  [SMALL_STATE(42)] = 380,
  [SMALL_STATE(43)] = 384,
  [SMALL_STATE(44)] = 388,
  [SMALL_STATE(45)] = 392,
  [SMALL_STATE(46)] = 396,
  [SMALL_STATE(47)] = 400,
  [SMALL_STATE(48)] = 404,
  [SMALL_STATE(49)] = 408,
  [SMALL_STATE(50)] = 412,
  [SMALL_STATE(51)] = 416,
  [SMALL_STATE(52)] = 420,
  [SMALL_STATE(53)] = 424,
  [SMALL_STATE(54)] = 428,
  [SMALL_STATE(55)] = 432,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_tag, 2, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_type, 1, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_param, 1, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_type_annotation, 3, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_tag, 3, 0, 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_param, 5, 0, 9),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_tag, 3, 0, 4),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_tag, 4, 0, 5),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_type, 4, 0, 7),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 3, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_member, 3, 0, 8),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_argument, 1, 0, 6),
  [117] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_default, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_default, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_default, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cypherdoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cypherdoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
