/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_STAR_STAR = 1,
  anon_sym_STAR_SLASH = 2,
  aux_sym_name_token1 = 3,
  sym_description_line = 4,
  anon_sym_ATparam = 5,
  anon_sym_ATreturns = 6,
  anon_sym_LBRACK = 7,
  anon_sym_EQ = 8,
  anon_sym_RBRACK = 9,
  aux_sym_string_default_token1 = 10,
  aux_sym_string_default_token2 = 11,
  sym_number_default = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_COMMA = 17,
  anon_sym_COLON = 18,
  sym_array_marker = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  sym_tag_description = 22,
  sym_document = 23,
  sym_name = 24,
  sym_description = 25,
  sym_param_tag = 26,
  sym_returns_tag = 27,
  sym_required_param = 28,
  sym_optional_param = 29,
  sym_param_default = 30,
  sym_string_default = 31,
  sym_boolean_default = 32,
  sym_type_annotation = 33,
  sym_returns_type_annotation = 34,
  sym_tuple_type = 35,
  sym_tuple_member = 36,
  sym_scalar_type = 37,
  sym_type_argument = 38,
  sym_identifier = 39,
  aux_sym_document_repeat1 = 40,
  aux_sym_description_repeat1 = 41,
  aux_sym_tuple_type_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_STAR_STAR] = "/**",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_name_token1] = "name_token1",
  [sym_description_line] = "description_line",
  [anon_sym_ATparam] = "@param",
  [anon_sym_ATreturns] = "@returns",
  [anon_sym_LBRACK] = "[",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACK] = "]",
  [aux_sym_string_default_token1] = "string_default_token1",
  [aux_sym_string_default_token2] = "string_default_token2",
  [sym_number_default] = "number_default",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_array_marker] = "array_marker",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_tag_description] = "tag_description",
  [sym_document] = "document",
  [sym_name] = "name",
  [sym_description] = "description",
  [sym_param_tag] = "param_tag",
  [sym_returns_tag] = "returns_tag",
  [sym_required_param] = "required_param",
  [sym_optional_param] = "optional_param",
  [sym_param_default] = "param_default",
  [sym_string_default] = "string_default",
  [sym_boolean_default] = "boolean_default",
  [sym_type_annotation] = "type_annotation",
  [sym_returns_type_annotation] = "returns_type_annotation",
  [sym_tuple_type] = "tuple_type",
  [sym_tuple_member] = "tuple_member",
  [sym_scalar_type] = "scalar_type",
  [sym_type_argument] = "type_argument",
  [sym_identifier] = "identifier",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_STAR_STAR] = anon_sym_SLASH_STAR_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_name_token1] = aux_sym_name_token1,
  [sym_description_line] = sym_description_line,
  [anon_sym_ATparam] = anon_sym_ATparam,
  [anon_sym_ATreturns] = anon_sym_ATreturns,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_string_default_token1] = aux_sym_string_default_token1,
  [aux_sym_string_default_token2] = aux_sym_string_default_token2,
  [sym_number_default] = sym_number_default,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_array_marker] = sym_array_marker,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_tag_description] = sym_tag_description,
  [sym_document] = sym_document,
  [sym_name] = sym_name,
  [sym_description] = sym_description,
  [sym_param_tag] = sym_param_tag,
  [sym_returns_tag] = sym_returns_tag,
  [sym_required_param] = sym_required_param,
  [sym_optional_param] = sym_optional_param,
  [sym_param_default] = sym_param_default,
  [sym_string_default] = sym_string_default,
  [sym_boolean_default] = sym_boolean_default,
  [sym_type_annotation] = sym_type_annotation,
  [sym_returns_type_annotation] = sym_returns_type_annotation,
  [sym_tuple_type] = sym_tuple_type,
  [sym_tuple_member] = sym_tuple_member,
  [sym_scalar_type] = sym_scalar_type,
  [sym_type_argument] = sym_type_argument,
  [sym_identifier] = sym_identifier,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATparam] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATreturns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_default_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_default_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number_default] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_array_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_description] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_param_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_required_param] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_default] = {
    .visible = true,
    .named = true,
  },
  [sym_string_default] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_default] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_member] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_column = 2,
  field_default = 3,
  field_description = 4,
  field_name = 5,
  field_param = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_column] = "column",
  [field_default] = "default",
  [field_description] = "description",
  [field_name] = "name",
  [field_param] = "param",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_param, 2},
    {field_type, 1},
  [4] =
    {field_description, 2},
    {field_type, 1},
  [6] =
    {field_description, 3},
    {field_param, 2},
    {field_type, 1},
  [9] =
    {field_value, 0},
  [10] =
    {field_argument, 2},
    {field_name, 0},
  [12] =
    {field_column, 0},
    {field_type, 2},
  [14] =
    {field_default, 3},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '"', 4,
        '\'', 5,
        '*', 9,
        ',', 78,
        '-', 32,
        '/', 8,
        ':', 79,
        '<', 81,
        '=', 66,
        '>', 82,
        '@', 22,
        '[', 65,
        ']', 67,
        'f', 38,
        't', 42,
        '{', 76,
        '}', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(46);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '@') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(46);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 4,
        '\'', 5,
        '*', 9,
        ',', 78,
        '-', 32,
        '/', 8,
        ':', 79,
        '<', 81,
        '=', 66,
        '>', 82,
        '@', 22,
        '[', 65,
        ']', 67,
        'f', 38,
        't', 42,
        '{', 76,
        '}', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') SKIP(31);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == 'f') ADVANCE(15);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead == '}') ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(35);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '*', 10,
        ',', 78,
        '-', 83,
        ':', 79,
        '<', 81,
        '=', 66,
        '>', 82,
        '@', 22,
        '[', 64,
        ']', 67,
        '}', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(80);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(60);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(13);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 31:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'a') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'e') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'e') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'l') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'r') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 's') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (lookahead == 'u') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '\t') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '@') ADVANCE(53);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(59);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'm') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'n') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'p') ADVANCE(48);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'r') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 's') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 't') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead == 'u') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_description_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATparam);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATparam);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_ATreturns);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_ATreturns);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ']') ADVANCE(80);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_string_default_token1);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_default_token2);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number_default);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number_default);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_array_marker);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_tag_description);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [aux_sym_name_token1] = ACTIONS(1),
    [anon_sym_ATparam] = ACTIONS(1),
    [anon_sym_ATreturns] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_string_default_token1] = ACTIONS(1),
    [aux_sym_string_default_token2] = ACTIONS(1),
    [sym_number_default] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_array_marker] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(47),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(5), 11,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      anon_sym_EQ,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_GT,
      sym_tag_description,
  [14] = 8,
    ACTIONS(7), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(9), 1,
      sym_description_line,
    ACTIONS(11), 1,
      anon_sym_ATparam,
    ACTIONS(13), 1,
      anon_sym_ATreturns,
    STATE(5), 1,
      sym_description,
    STATE(9), 1,
      aux_sym_description_repeat1,
    STATE(46), 1,
      sym_returns_tag,
    STATE(6), 2,
      sym_param_tag,
      aux_sym_document_repeat1,
  [40] = 5,
    ACTIONS(17), 1,
      sym_number_default,
    STATE(52), 1,
      sym_param_default,
    ACTIONS(15), 2,
      aux_sym_string_default_token1,
      aux_sym_string_default_token2,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 2,
      sym_string_default,
      sym_boolean_default,
  [59] = 5,
    ACTIONS(21), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(23), 1,
      anon_sym_ATparam,
    ACTIONS(25), 1,
      anon_sym_ATreturns,
    STATE(56), 1,
      sym_returns_tag,
    STATE(7), 2,
      sym_param_tag,
      aux_sym_document_repeat1,
  [76] = 5,
    ACTIONS(21), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(23), 1,
      anon_sym_ATparam,
    ACTIONS(25), 1,
      anon_sym_ATreturns,
    STATE(56), 1,
      sym_returns_tag,
    STATE(10), 2,
      sym_param_tag,
      aux_sym_document_repeat1,
  [93] = 5,
    ACTIONS(23), 1,
      anon_sym_ATparam,
    ACTIONS(25), 1,
      anon_sym_ATreturns,
    ACTIONS(27), 1,
      anon_sym_STAR_SLASH,
    STATE(45), 1,
      sym_returns_tag,
    STATE(10), 2,
      sym_param_tag,
      aux_sym_document_repeat1,
  [110] = 4,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    STATE(15), 1,
      sym_identifier,
    STATE(14), 2,
      sym_required_param,
      sym_optional_param,
  [124] = 3,
    ACTIONS(35), 1,
      sym_description_line,
    STATE(11), 1,
      aux_sym_description_repeat1,
    ACTIONS(33), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [136] = 3,
    ACTIONS(39), 1,
      anon_sym_ATparam,
    ACTIONS(37), 2,
      anon_sym_STAR_SLASH,
      anon_sym_ATreturns,
    STATE(10), 2,
      sym_param_tag,
      aux_sym_document_repeat1,
  [148] = 3,
    ACTIONS(44), 1,
      sym_description_line,
    STATE(11), 1,
      aux_sym_description_repeat1,
    ACTIONS(42), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [160] = 1,
    ACTIONS(47), 4,
      anon_sym_STAR_SLASH,
      sym_description_line,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [167] = 2,
    ACTIONS(51), 1,
      anon_sym_LT,
    ACTIONS(49), 3,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [176] = 2,
    ACTIONS(55), 1,
      sym_tag_description,
    ACTIONS(53), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [185] = 1,
    ACTIONS(57), 4,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      sym_tag_description,
  [192] = 1,
    ACTIONS(59), 4,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
      sym_tag_description,
  [199] = 3,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    STATE(21), 1,
      sym_tuple_member,
    STATE(39), 1,
      sym_identifier,
  [209] = 3,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    STATE(13), 1,
      sym_identifier,
    STATE(54), 1,
      sym_scalar_type,
  [219] = 3,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    STATE(41), 1,
      sym_type_argument,
    STATE(42), 1,
      sym_identifier,
  [229] = 1,
    ACTIONS(61), 3,
      anon_sym_STAR_SLASH,
      anon_sym_ATparam,
      anon_sym_ATreturns,
  [235] = 3,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_tuple_type_repeat1,
  [245] = 3,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    STATE(36), 1,
      sym_tuple_member,
    STATE(39), 1,
      sym_identifier,
  [255] = 3,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_tuple_type_repeat1,
  [265] = 3,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    STATE(13), 1,
      sym_identifier,
    STATE(38), 1,
      sym_scalar_type,
  [275] = 1,
    ACTIONS(69), 3,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [281] = 3,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym_tuple_type_repeat1,
  [291] = 2,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_returns_type_annotation,
  [298] = 2,
    ACTIONS(29), 1,
      aux_sym_name_token1,
    STATE(48), 1,
      sym_identifier,
  [305] = 2,
    ACTIONS(78), 1,
      anon_sym_LBRACK,
    STATE(57), 1,
      sym_tuple_type,
  [312] = 1,
    ACTIONS(80), 2,
      aux_sym_name_token1,
      anon_sym_LBRACK,
  [317] = 2,
    ACTIONS(82), 1,
      aux_sym_name_token1,
    STATE(3), 1,
      sym_name,
  [324] = 2,
    ACTIONS(84), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_type_annotation,
  [331] = 2,
    ACTIONS(86), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(88), 1,
      sym_tag_description,
  [338] = 1,
    ACTIONS(90), 2,
      anon_sym_STAR_SLASH,
      sym_tag_description,
  [343] = 2,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      sym_array_marker,
  [350] = 1,
    ACTIONS(71), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [355] = 2,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 1,
      sym_array_marker,
  [362] = 1,
    ACTIONS(100), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [367] = 1,
    ACTIONS(102), 1,
      anon_sym_COLON,
  [371] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [375] = 1,
    ACTIONS(106), 1,
      anon_sym_GT,
  [379] = 1,
    ACTIONS(108), 1,
      anon_sym_GT,
  [383] = 1,
    ACTIONS(110), 1,
      anon_sym_STAR_SLASH,
  [387] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [391] = 1,
    ACTIONS(114), 1,
      anon_sym_STAR_SLASH,
  [395] = 1,
    ACTIONS(21), 1,
      anon_sym_STAR_SLASH,
  [399] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [403] = 1,
    ACTIONS(118), 1,
      anon_sym_EQ,
  [407] = 1,
    ACTIONS(120), 1,
      anon_sym_RBRACK,
  [411] = 1,
    ACTIONS(122), 1,
      anon_sym_RBRACK,
  [415] = 1,
    ACTIONS(124), 1,
      anon_sym_RBRACK,
  [419] = 1,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
  [423] = 1,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
  [427] = 1,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
  [431] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [435] = 1,
    ACTIONS(27), 1,
      anon_sym_STAR_SLASH,
  [439] = 1,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
  [443] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [447] = 1,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 59,
  [SMALL_STATE(6)] = 76,
  [SMALL_STATE(7)] = 93,
  [SMALL_STATE(8)] = 110,
  [SMALL_STATE(9)] = 124,
  [SMALL_STATE(10)] = 136,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 160,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 176,
  [SMALL_STATE(15)] = 185,
  [SMALL_STATE(16)] = 192,
  [SMALL_STATE(17)] = 199,
  [SMALL_STATE(18)] = 209,
  [SMALL_STATE(19)] = 219,
  [SMALL_STATE(20)] = 229,
  [SMALL_STATE(21)] = 235,
  [SMALL_STATE(22)] = 245,
  [SMALL_STATE(23)] = 255,
  [SMALL_STATE(24)] = 265,
  [SMALL_STATE(25)] = 275,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 291,
  [SMALL_STATE(28)] = 298,
  [SMALL_STATE(29)] = 305,
  [SMALL_STATE(30)] = 312,
  [SMALL_STATE(31)] = 317,
  [SMALL_STATE(32)] = 324,
  [SMALL_STATE(33)] = 331,
  [SMALL_STATE(34)] = 338,
  [SMALL_STATE(35)] = 343,
  [SMALL_STATE(36)] = 350,
  [SMALL_STATE(37)] = 355,
  [SMALL_STATE(38)] = 362,
  [SMALL_STATE(39)] = 367,
  [SMALL_STATE(40)] = 371,
  [SMALL_STATE(41)] = 375,
  [SMALL_STATE(42)] = 379,
  [SMALL_STATE(43)] = 383,
  [SMALL_STATE(44)] = 387,
  [SMALL_STATE(45)] = 391,
  [SMALL_STATE(46)] = 395,
  [SMALL_STATE(47)] = 399,
  [SMALL_STATE(48)] = 403,
  [SMALL_STATE(49)] = 407,
  [SMALL_STATE(50)] = 411,
  [SMALL_STATE(51)] = 415,
  [SMALL_STATE(52)] = 419,
  [SMALL_STATE(53)] = 423,
  [SMALL_STATE(54)] = 427,
  [SMALL_STATE(55)] = 431,
  [SMALL_STATE(56)] = 435,
  [SMALL_STATE(57)] = 439,
  [SMALL_STATE(58)] = 443,
  [SMALL_STATE(59)] = 447,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_type, 1, 0, 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_tag, 3, 0, 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_param, 1, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_param, 5, 0, 9),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_tag, 4, 0, 5),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_type, 4, 0, 7),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 3, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_tag, 2, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_type_annotation, 3, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_member, 3, 0, 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 6, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_argument, 1, 0, 6),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_tag, 3, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 5, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_default, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_default, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_default, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cypherdoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cypherdoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
